### ISSUE TITLE
[Feature] HomePage should display loading icon like time-table page

### ISSUE THREAD

**Issue by angrezichatterbox** [Bunk-Mate/Mobile-App#41]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I navigate to the HomePage and experience delays in loading without any indication of progress. It can be unclear whether the page is still loading or if there’s an error as it always shows that No courses are available initially. 

**Describe the solution you'd like**
I would like the HomePage to display a loading icon, similar to what is used on the time-table page. This would provide users with a visual cue that the content is being loaded, improving the overall user experience.

**Describe alternatives if applicable**
An alternative could be to implement a simple text message indicating that the page is loading, but I believe a loading icon would be more effective and visually appealing. Additionally, using a progress bar could also be considered, but it may be more complex to implement.

**Comment by 98021Varundeep** [comment]
Hi @angrezichatterbox ,
 i would like to work on this issue, 
And kindly conform which logo we want for Home Page, not clear thorugh description,

**Comment by angrezichatterbox** [comment]
Feel free to work on this issue. 

So, currently, when the user opens the home page, it shows that no courses are available, even if they are available, as it takes time to fetch them from the backend. The issue is to make the loading icon show up initially when the page loads up as it waits for the result to be fetched. If the fetched result is empty then show that there are no courses.

**Comment by angrezichatterbox** [comment]
Closing this with #42. Thanks for your hard work, @98021Varundeep! Would you be interested in looking into the other issues as well? 😊
