### ISSUE TITLE
[BUG] Rename app title to Bunk Mate

### ISSUE THREAD

**Issue by ItsAbhinavM** [Bunk-Mate/Mobile-App#44]
**Description**

The app title in the navigation drawer is named as Flutter Demo which needs to be changed to the actual application name.

**Screenshots**

![app_title](https://github.com/user-attachments/assets/63377f38-ad2d-4213-8932-064d2517b4a5)

**Platform:**
* - [x] Android
* - [x] iOS

**Comment by angrezichatterbox** [comment]
Closed by #45. Thanks a lot @andi-mache. Hope we can see you contributing more to the Bunk-Mate project.
